---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: momo-store
    env: "{{ .Values.environment }}" 
spec:
  # желаемое количество реплик Pod'а
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 12
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 20%
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    # шаблон для создания Pod'ов
    spec:
      containers:
        - image: "{{ .Values.image }}:lastest"
          name: {{ .Chart.Name }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: backend-port
              containerPort: 8081
      # чтобы Кубер мог скачивать образы из нашего GitLab Registry
      imagePullSecrets:
        - name: docker-config-secret
