---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: "{{ .Chart.Name }}-{{ .Release.Name }}"
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: "{{ .Chart.Name }}-{{ .Release.Name }}"
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: ["cpu", "memory"]
        controlledValues: RequestsOnly