variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  # - build
  - test
  # - release

include:
  - template: Security/SAST.gitlab-ci.yml

backend-go-test:
  stage: test
  image: golang:1.17
  only:
    changes:
      - backend/**/*
  script:
    - cd backend
    - go test -v ./...

sonarqube-backend-sast:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  only:
    changes:
      - backend/**/*
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - "sonar-scanner -Dsonar.qualitygate.wait=true -X
      -Dsonar.projectKey=${SONAR_DIPLOM_KEY_BACK}
      -Dsonar.sources=backend
      -Dsonar.host.url=${SONAR_DIPLOM_URL}
      -Dsonar.login=${SONAR_DIPLOM_LOGIN_BACK}"
