include:
  - template: Terraform.latest.gitlab-ci.yml
  - template: Jobs/SAST-IaC.latest.gitlab-ci.yml

stages:
  - validate
  - test
  - build
  - deploy
  - destroy

variables:
  TF_CLI_CONFIG_FILE: ${CI_PROJECT_DIR}/infra/terraform/.terraformrc
  TF_ROOT: ${CI_PROJECT_DIR}/infra/terraform/
  TF_STATE_NAME: x${CI_ENVIRONMENT_NAME}

fmt:
  extends: .terraform:fmt

validate:
  extends: .terraform:validate

plan:
  extends: .terraform:build

deploy:
  extends: .terraform:deploy
  environment:
    name: $TF_STATE_NAME
    on_stop: destroy

destroy:
  stage: destroy
  extends: .terraform:destroy
  environment:
    name: $TF_STATE_NAME
    action: stop
