include:
  - template: Terraform/Base.gitlab-ci.yml
  - template: Jobs/SAST-IaC.latest.gitlab-ci.yml

stages:
  - validate
  - test
  - build
  - deploy
  - destroy

variables:
  TF_CLI_CONFIG_FILE: ${CI_PROJECT_DIR}/infra/terraform/.terraformrc
  TF_ROOT: ${CI_PROJECT_DIR}/infra/terraform/
  TF_STATE_NAME: x${CI_ENVIRONMENT_NAME}

validate:
  extends: .terraform:validate

build:
  extends: .terraform:build

deploy:
  extends: .terraform:deploy
  environment:
    name: $TF_STATE_NAME
    on_stop: destroy

terraform_apply:
  needs:
    - build
  stage: deploy
  script:
    - terraform apply ${TF_ROOT}/plan.json
  when: manual

destroy:
  stage: destroy
  extends: .terraform:destroy
  environment:
    name: $TF_STATE_NAME
    action: stop
