include:
  - template: Terraform.latest.gitlab-ci.yml

variables:
  TF_CLI_CONFIG_FILE: ${CI_PROJECT_DIR}/infra/terraform/.terraformrc

deploy:
  environment:
    name: $TF_STATE_NAME
    action: start
    on_stop: destroy

destroy:
  extends: .terraform:destroy
  environment:
    name: $TF_STATE_NAME
    action: stop

destroy_manual:
  extends: .terraform:destroy
  environment:
    name: $TF_STATE_NAME
    action: stop
  when: manual