---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    # Хост определяет правило направления траффика по доменному имени
  - host: {{ .Values.host }}
    http:
      # Для различных путей в URL можно указать различные бэкенд-сервисы
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # Заранее создан сервис типа ClusterIP
            # Он выступает в качестве бэкенда нашего Ingress
            name: {{ .Chart.Name }}
            port:
              # У сервиса может быть несколько портов, указываем нужный нам
              number: 80
      - path: /products
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8081
      - path: /categories
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8081
      - path: /orders
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8081
      - path: /auth/whoami
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8081
      - path: /
        pathType: Prefix
        backend:
          service:
            # Заранее создан сервис типа ClusterIP
            # Он выступает в качестве бэкенда нашего Ingress
            name: {{ .Chart.Name }}
            port:
              # У сервиса может быть несколько портов, указываем нужный нам
              number: 443