stages:
  - test

before_script: #Проба установить хэлм
  - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
  - chmod 700 get_helm.sh
  - ./get_helm.sh

test-job: 
  stage: test
  script:
  - ls -la
  - helm version